### ISSUE TITLE
Repository status?

### ISSUE THREAD

**Issue by paralin** [GoogleCloudPlatform/gcloud-dotnet#1]
Are there plans to start work on this sometime soon? I'm really missing the support in C#

**Comment by paralin** [comment]
Ah, I guess https://www.nuget.org/packages/Google.Apis/ exists. What's the status of this repo, then?

**Comment by jskeet** [comment]
This repo is going to consist of wrappers around lower level API libraries to make them significantly easier (and more idiomatic) to use.

You can see some prototyping work in my fork here:

https://github.com/jskeet/gcloud-dotnet/tree/experimental-gcs

**Comment by jskeet** [comment]
Now that I've started merging things into the repo, hopefully things are becoming clearer. Closing for now - feel free to reopen.
