### ISSUE TITLE
Error reading default credentials file using Newtonsoft.Json v8

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/gcloud-dotnet#102]
The call to Google.Storage.V1.StorageClient.FromApplicationCredentials() works using Newtonsoft.Json 7.x, but fails when upgrading to 8.x.

This behavior happens when debugging this sample: https://github.com/csells/GoogleStorageProvider/tree/e4f2436cbf951c0d522f8c73ac72beae54d76a38

Enter the PowerShell command "dir gcs:\" to see the problem.

Following the error's recommendation to "Please rerun 'gcloud auth login' to regenerate credentials file" does not fix the problem.

**Comment by chrsmith** [comment]
This is actually not possible to fix.

You get that error message (rerun gcloud auth login) because in the bowels of the Apiary client library, an exception is thrown when trying to parse the credentials JSON file. That exception is "could not find `Newtonsoft.Json 7.x`.

Why is it looking for Newtonsoft.Json 7.x? Because the Apiary client libraries (Google.Apis.dll) has a dependency on it. Normally users don't run into these problems because an assembly redirect is put in `app.config` by NuGet. However, PowerShell doesn't honor your project's app.config file because of the way cmdlets are loaded. (There is no notion of an assembly-specific config file, to my knowledge.)

So you could work around this by putting the assembly redirect in your `machine.config` file. Or just downgrade to Newtonsoft 7.x when using PowerShell until the Apiary client libraries upgrade to 8.0. As for upgrading the Apiary client libraries to use Newtonsoft 8.0, there is nothing stopping us from doing that. I think it is just a matter of thinking harder about it and confirming it won't break anybody.

**Comment by chrsmith** [comment]
To reiterate, this should only be blocking scenarios where the consumer of the `gcloud-dotnet` project is an assembly, and not a stand-alone executable. Since the stand-alone executable path will use an app.config file.

**Comment by csells** [comment]
How do I tell that this is a “would need an app.config” file bug (as it was before) vs. a “we’ve got a build process stamping the wrong version on things” bug or a “Newtonsoft.JSON has tighten the JSON that they read and our mostly-by-not-completely-correct JSON credentials file is no longer correct” bug (which is what I thought it was)? Does any entry in the app.config signal trouble? Do we know the algorithm to detect this kind of problem in the future? Given the algorithm, I’m happy to write a tool to avoid this problem in the future.


On Apr 11, 2016, at 8:25 AM, Chris Smith <notifications@github.com<mailto:notifications@github.com>> wrote:


This is actually not possible to fix.

You get that error message (rerun gcloud auth login) because in the bowels of the Apiary client library, an exception is thrown when trying to parse the credentials JSON file. That exception is "could not find Newtonsoft.Json 7.x.

Why is it looking for Newtonsoft.Json 7.x? Because the Apiary client libraries (Google.Apis.dll) has a dependency on it. Normally users don't run into these problems because an assembly redirect is put in app.config by NuGet. However, PowerShell doesn't honor your project's app.config file because of the way cmdlets are loaded. (There is no notion of an assembly-specific config file, to my knowledge.)

So you could work around this by putting the assembly redirect in your machine.config file. Or just downgrade to Newtonsoft 7.x when using PowerShell until the Apiary client libraries upgrade to 8.0. As for upgrading the Apiary client libraries to use Newtonsoft 8.0, there is nothing stopping us from doing that. I think it is just a matter of thinking harder about it and confirming it won't break anybody.

**Comment by jskeet** [comment]
One option would be to stop being quite so liberal with the exceptions we catch in https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/GoogleApis.Auth.DotNet4/OAuth2/DefaultCredentialProvider.cs

If we had a specific set of error scenarios in mind, tested what exception is thrown in each of them, and then caught only those exceptions (and gave great error messages) this would be much cleaner.

Perhaps we should move this bug over to https://github.com/google/google-api-dotnet-client now?

**Comment by csells** [comment]
I’m wary of us catching a “bug” that’s by design as far as Microsoft is concerned. I was thinking more along the lines of a post-build tool that would perhaps check for a non-empty app.config? Or check the entries in the app.config against the dependent versions? I’m not sure what the right think to check for, actually.


On Apr 11, 2016, at 9:17 AM, Jon Skeet <notifications@github.com<mailto:notifications@github.com>> wrote:


One option would be to stop being quite so liberal with the exceptions we catch in https://github.com/google/google-api-dotnet-client/blob/master/Src/Support/GoogleApis.Auth.DotNet4/OAuth2/DefaultCredentialProvider.cs

If we had a specific set of error scenarios in mind, tested what exception is thrown in each of them, and then caught only those exceptions (and gave great error messages) this would be much cleaner.

Perhaps we should move this bug over to https://github.com/google/google-api-dotnet-client now?

**Comment by jskeet** [comment]
We only need a non-empty app.config in cases where assembly binding redirects are actually required. I think the fact that the error message suggested the wrong course of action is the first thing to fix - if it were obvious that this is a type load failure, what bug would you have filed? (Not saying it wouldn't have been worth filing one, but I think it would have been different.)

I'd also be interested in thinking about how this would be caught by testing of the customer's code - if it's always caught in any tests that exercise the API at all, I'm not sure that a post-build tool gives much more benefit...

**Comment by jskeet** [comment]
@csells: Any thoughts on whether we can close this as basically infeasible? We're basically in the same situation as all other projects that take other dependencies.

**Comment by jskeet** [comment]
Closing as "won't fix" until anyone comes up with a better idea.
