### ISSUE TITLE
"Improve this Doc" link is broken in API documentation page

### ISSUE THREAD

**Issue by chrsmith** [GoogleCloudPlatform/gcloud-dotnet#103]
The "Improve this Doc" button/link leads to a 404 from the API docs page. Let's get this to work if we can, otherwise just remove it from the template.

http://googlecloudplatform.github.io/gcloud-dotnet/

**Comment by jskeet** [comment]
Looks like this is what I need: https://github.com/dotnet/docfx/issues/120

**Comment by jskeet** [comment]
It disables the "View source" button as well, which is unfortunate - but it's probably better than nothing for now.
