### ISSUE TITLE
ListX vs. ListAllXAsync pattern confusing

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/gcloud-dotnet#115]
Does ListBuckets and ListObjects somehow not list *all* buckets or objects? The .NET convention is to have Foo/FooAsync. Can we have ListX/ListXAsync or ListAllX/ListAllXAsync (ideally the former, since it's shorter)?

**Comment by jskeet** [comment]
The difference is that `ListBuckets` is lazy, whereas `ListAllBucketsAsync` isn't - the task for the latter will only complete when all the buckets have been retrieved.

We used to have `ListBucketsAsync` returning an `IAsyncEnumerable<>` but that was removed when we moved a lot of the logic to `Google.Apis.Core`, in order to avoid taking a dependency on Ix-Async.

We should work out for sure what operations we want to support, and then work out the names for them.
See also: #12.

**Comment by csells** [comment]
I would argue that logically both methods are the same. Calling each one means "I'd like a list of all of the buckets, please." In the case of the sync version, we're calling in a lazy way based on page size as an optimization to reduce round-trips, but logically both are the same. Can we just call them ListObjects and ListObjectsAsync?

**Comment by chrisdunelm** [comment]
But the performance of the methods is distinctly different.
The ListBuckets method will initially block for a maximum of one RPC, whereas the task returned by ListAllBucketsAsync will not complete until after an arbitrary number of RPCs which depends on the total number of buckets to return.

It seems to me highly preferable that the async method should return something similar to IAsyncEnumerable here, which gives more useful and predictable behaviour.

Could we define our own IAsyncEnumerable<> (possibly with a different name?) interface within our package?
So we get the desirable behaviour, without the Ix-Async dependency?

We could provide all four of the possible methods, which allows the user to select for the performance/complexity they require.:
IEnumerable<X> ListX() // Lazy, retrieves X's lazily, MoveNext will block when another RPC is required
IEnumerable<X> ListAllX() // Eager, doesn't return until all X are retrieved
IOurAsyncEnumerable<X> ListXAsync() // Lazy, task returned by MoveNext will take time when another RPC is required
Task<IEnumerable<X>> ListAllXAsync() // Eager, task doesn't complete until all X are retrieved

**Comment by csells** [comment]
Can we provide two methods, sync and async, and drive the differences in laziness via arguments?

But the performance of the methods is distinctly different.
The ListBuckets method will initially block for a maximum of one RPC, whereas the task returned by ListAllBucketsAsync will not complete until after an arbitrary number of RPCs which depends on the total number of buckets to return.

It seems to me highly preferable that the async method should return something similar to IAsyncEnumerable here, which gives more useful and predictable behaviour.

Could we define our own IAsyncEnumerable<> (possibly with a different name?) interface within our package?
So we get the desirable behaviour, without the Ix-Async dependency?

We could provide all four of the possible methods, which allows the user to select for the performance/complexity they require.:
IEnumerable ListX() // Lazy, retrieves X's lazily, MoveNext will block when another RPC is required
IEnumerable ListAllX() // Eager, doesn't return until all X are retrieved
IOurAsyncEnumerable ListXAsync() // Lazy, task returned by MoveNext will take time when another RPC is required
Task> ListAllXAsync() // Eager, task doesn't complete until all X are retrieved

-

**Comment by jskeet** [comment]
(Edited csells comment down as it was effectively quoting that of chrisdunelm.)

**Comment by chrisdunelm** [comment]
Possibly we could for the sync case.
For the async case the return types are currently different:
Task<IEnumerable<X>> for eager
IAsyncEnumerable<X> for lazy.

Of course, the eager async could return an IAsyncEnumerable<X>, with the the very first MoveNext() task not completing until all the items have been retrieved. But this (in my opinion) would be an unexpected use of IAsyncEnumerable.

Also, Jon pointed out that implementing our own IAsyncEnumerable (so a dep on Ix-Async isn't required) isn't great as we won't want to implement all the various extension methods that Ix-Async provide that make all the wonderful LINQy magic happen.

**Comment by csells** [comment]
The standard trick there, of course, is to vary the arguments to a method so that you can vary the return type.

**Comment by jskeet** [comment]
Just to update, we're looking at this more generally, so that we have the same pattern for gRPC-based APIs and REST-based APIs. This may well mean that we can't end up using `PageStreamer`, but I'm fine for us to take that hit. We're hoping to have some answers here reasonably soon - the gRPC changes are likely to come first, but I'll then apply the same changes to Storage and Bigquery.

**Comment by jskeet** [comment]
I'm going to start prototyping this today. I think we'll want to have a separate common library for it.

**Comment by jskeet** [comment]
We've now updated to a consistent page-streaming approach for both the REST and gRPC-based APIs.
