### ISSUE TITLE
Missing Bucket methods

### ISSUE THREAD

**Issue by csells** [GoogleCloudPlatform/gcloud-dotnet#116]
We have ListBuckets, but no CreateBucket, GetBucket or DeleteBucket. Can we add those as well? The code is certainly doable by dropping down into the Service object, but the number of times I forget to call Execute is staggering.

**Comment by jskeet** [comment]
All of this is possible. I basically stopped after implementing the highest priority operations. I suspect that GetBucket is less useful in general than CreateBucket or DeleteBucket, but I could be wrong.

We should talk about prioritization between operations within here, and also work on other APIs.

**Comment by csells** [comment]
Agreed. P2.

**Comment by jskeet** [comment]
These are now all implemented.
