### ISSUE TITLE
How do we want to model asynchronous collection fetching?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/gcloud-dotnet#12]
Scenario: I want to fetch many books from the bookshelf, but I don't want to do all the paging myself. The client should just do that for me, right?

For the synchronous approach, that's easy - I can return an `IEnumerable<Book>` and use an iterator block, fetching the next page when I need to. (At a later date we can consider background fetching...)

For the asynchronous approach, I've currently got two methods in my common pagination support class:
- `FetchAsync`, returns an `IAsyncEnumerable<Book>` (where `IAsyncEnumerable<T>` is defined in the Ix-Async library)
- `FetchAllAsync`, returns a `Task<IList<Book>>`

The idea being that sometimes I want to iterate (asynchronously) and lazily perform the requests, and other times I just want to get the whole lot, asynchronously.

So far, so good.

Proposal: Ditch `FetchAllAsync`, and just have the method returning `IAsyncEnumerable<Book>`

Concern: Help, I don't know what one of those is! I just want a list!

Mitigation: That's okay, call `ToList(CancellationToken)` on it, and you get a `Task<List<Book>>`. That functionality is provided by Ix-Async already... along with other standard LINQ operators, and `ForEachAsync` etc.

So it's definitely easy to do what you want with an `IAsyncEnumerable<T>`, but do we think it's discoverable enough? I'm pretty sure that developers will know what to do with a `Task<IList<Book>>`, but I would prefer to just have one async method and one sync method if possible. (They're going to be overloaded anyway, and we need to be careful with naming etc...)

**Comment by ivannaranjo** [comment]
The IAsyncEnumerable patterns are so new that I thin that we need to consider them pretty much unknown, so we might have to provide the extra overload to help with these scenarios. I personally think that the `ToList` scenario are particularly common server side workloads for the case when the developer doesn't want to deal with pages, so having the extra _All_ overloads should help with that case. For clientside development (if we also want to consider that) direct paging support is probably more interesting to be able to hook up into UI elements that databind to remote collections.

**Comment by jskeet** [comment]
I'm hoping that UI elements will have suitable `IAsyncEnumerable<T>` bindings at some point.
But yes, you've basically confirmed what I was thinking. I could still get rid of the Paginator part, of course, and just make `ListAllBooksAsync` (or whatever) call `ToList` itself.

**Comment by ivannaranjo** [comment]
Look at, https://msdn.microsoft.com/library/windows/apps/Hh701916, which is
close to this... :)

**Comment by jskeet** [comment]
Removing PR #13 now, as the merged code is mostly there - basically it's a matter of deciding whether we also want to remove (or rename) the `ListAll` methods. The "All" may imply no filtering is performed, whereas there's the same filtering as normal - it's just a matter of fetching everything before the task completes.

**Comment by jskeet** [comment]
// cc @mmdriley @chrsmith @csells

**Comment by chrsmith** [comment]
I'm unfamiliar with `IAsyncEnumerable` but I do think we should avoid requiring users to go through an extra step of indirection if possible. i.e. I'd advocate for having a `FetchAll[Async]` method which "just works". Getting all of the items in a collection (and not needing to worry about paging) is probably the 80-90% case.

Am I correct in thinking that `IAsyncEnumerable` is basicly an `IEnumerable<Task<IEnumerable<T>>`? With the outer enumerator being each page of results? If so, having that for the advanced scenario when you want to do something smart with each page (e.g. have a "Next" button in the UI) should be possible.

**Comment by jskeet** [comment]
No, from the client's perspective it's not that - there's `GetEnumerator` as normal, then `Task<bool> MoveNext(CancellationToken)` on the `IAsyncEnumerator<T>`. Our *implementation* goes via pages, but that's hidden from the caller - they just see as sequence of items that are fetched asynchronously.

Sounds like the `FetchAllAsync` has the vote to stay though.

**Comment by mmdriley** [comment]
Yes, like [File.ReadLines](https://msdn.microsoft.com/en-us/library/dd383503(v=vs.110).aspx) and [File.ReadAllLines](https://msdn.microsoft.com/en-us/library/s2tte0y1(v=vs.110).aspx), we'll have the efficient one and the easy/discoverable one. :)

**Comment by jskeet** [comment]
This appears to be decided - although note that for GCS, we're not taking a dependency on IxAsync, so there's only "fetch all, asynchronously".
