### ISSUE TITLE
Make StorageClient.Service throw NotImplementedException

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/gcloud-dotnet#126]
(To match the gRPC equivalent code.)

**Comment by csells** [comment]
Under what circumstances would it throw such an exception? Isn't this the way that I get to the underlying Apiary service object for things that the Veneer doesn't do?

**Comment by jskeet** [comment]
It will do it if you've mocked the abstract class but not overridden that part.

It will never do it under normal circumstances, where you've got a StorageClientImpl.

**Comment by csells** [comment]
OK. Good.

On Apr 28, 2016, at 6:41 AM, Jon Skeet <notifications@github.com<mailto:notifications@github.com>> wrote:


It will do it if you've mocked the abstract class but not overridden that part.

It will never do it under normal circumstances, where you've got a StorageClientImpl.
