### ISSUE TITLE
Discoverability of .Flatten() and .WithFixedPageSize() methods

### ISSUE THREAD

**Issue by chrisdunelm** [GoogleCloudPlatform/gcloud-dotnet#157]
The IPagedEnumerable\<...> (and IPagedAsyncEnumerable\<...>) .Flatten() and WithFixedPageSize() extension methods are in namespace Google.Api.Gax, possibly making them less discoverable than we might like.
Should we add these methods to the interfaces, given that we don't expect anyone else to implement these interfaces?

**Comment by jskeet** [comment]
Yes, I think that would be a good idea. Having used this a couple of times now, the discoverability could certainly be better.

**Comment by jskeet** [comment]
Assigning myself as I can do this in a PR before taking off for vacation...
