### ISSUE TITLE
Update copyright footer in generated documentation

### ISSUE THREAD

**Issue by jsimonweb** [GoogleCloudPlatform/gcloud-dotnet#167]
Update the copyright footer in the generated documentation pages at: http://googlecloudplatform.github.io/gcloud-dotnet/

**Comment by jskeet** [comment]
This is currently hard-coded in the docfx template.
Have raised https://github.com/dotnet/docfx/issues/324

Obviously we'll want to create our own template at some point anyway, but I'm sure we're not the only ones this will bite...
