### ISSUE TITLE
Should options be cloneable?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/gcloud-dotnet#20]
Our conventions already state that the wrapper library shouldn't modify the options... should we make the options cloneable? In some cases, the caller may have some "common" options between calls, but some options they wish to change per call. They *may* prefer to write a clone method to do this - although in most cases a common method using an object initializer would be simpler.

Up for discussion.

**Comment by SurferJeffAtGoogle** [comment]
Yes.  That seems convenient.

**Comment by jskeet** [comment]
// cc @ivannaranjo @mmdriley @chrsmith @csells

**Comment by ivannaranjo** [comment]
Indeed they should, and furthermore methods accepting options should clone the object before any asynchronous operation begins, to ensure a consistent set of options throughout the execution of the operation.

**Comment by chrsmith** [comment]
I agree it is convenient, but `.clone()` is more common in the Java world, right? In C# it is more common to have value types (`struct`s and relying on structural equality).

IMHO it would be better to either 1.) not do anything and rely on an object initializer or 2.) just create a constructor that takes an existing option and we mutate that object. (e.g. .ctor > a clone method).

**Comment by ivannaranjo** [comment]
I could see the constructor doing the clonning, the collections in essence
do the same thing. I would also add the case of an *internal* Clone method
to support the case of cloning the value to avoid multi-thread and
re-entrancy issues without having to offer it up as a public API.

**Comment by jskeet** [comment]
For the gRPC code, we're adopting a pattern of:

- Provide a `Clone` method for the convenience of clients who want to
- Don't actually clone settings, and document that they shouldn't be changed while they're used (with "while they're used" documented too; it depends on the setting)
- Clone things which the client may well expect to be able to change, e.g. requests when bundling

Will leave this issue open for the moment as we should document this convention.

**Comment by jskeet** [comment]
We're not providing any cloning for the REST-based APIs. I think I'm happy to close this now.
