### ISSUE TITLE
Add support for the App Engine Admin API

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/gcloud-dotnet#205]
We have an Admin API (service management) for App Engine here:
https://cloud.google.com/appengine/docs/admin-api/reference/rest/

It's a pretty basic CRUD / REST style API, but it would be great to have wrappers that make it easier to use.

**Comment by jskeet** [comment]
There are *lots* of APIs that we could add extra support for. We'll be going through internal processes to determine the best place to put our resources. I'm going to close this issue for the moment as leaving it open would give precedent to lots of feature requests along the same lines, without much signal coming out of it. Feel free to contact the team internally though...
