### ISSUE TITLE
Consider policy for chaining async calls

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/gcloud-dotnet#22]
Suppose we have `Task Foo(string)` and `Task Foo(int)` where the string-parameter version is equivalent to calling the int-parameter version with the length of the string as its argument.

This can be implemented as:

```csharp
public Task Foo(string x)
{
  Preconditions.CheckNotNull(x);
  return Foo(x.Length);
}
```

or

```csharp
public async Task Foo(string x)
{
  Preconditions.CheckNotNull(x);
  await Foo(x.Length).ConfigureAwait(false);
}
```

They differ in terms of whether `Foo(null)` throws an `ArgumentNullException` directly, or returns a task that is faulted instead.

The first option is very slightly more efficient, but the implementation detail of when the check is performed leaks to callers. Options:

1. Make sure that *all* preconditions are checked synchronously (an exception is thrown), chaining to private async methods if necessary.
2. Make sure that *all* preconditions are checked asynchronously (a faulted task is returned)
3. Don't worry too much about being consistent, and just use the simplest code in each case

Option 1 will lead to harder-to-read code. Option 2 will lead to slight inefficiencies. Option 3 leads to code which is easy to read and maintain, but less consistent for callers. They may never actually notice, but the inconsistency is still there.

I'm not sure what Microsoft code does here...

**Comment by SurferJeffAtGoogle** [comment]
I like the first example better.  I don't think it's worthwhile to try to
check all preconditions are checked synchronously.  We can't guarantee that
exceptions will only be thrown during precondition checks, so it doesn't
reduce the burden of catching exceptions.

Also, if any of the code is as simple as this toy example, I'd prefer to
see the precondition omitted entirely.  Foo(x.Length) will fail with a
reasonable error message and the same stack trace as
Precondition.CheckNotNull().  We can document that the param must not be
null in the block comment with a <param name="x">must not be null</param>.
This will give the caller an indication that the param must not be null
even before they compile.

**Comment by jskeet** [comment]
So that's option 3, basically.

But I *would* include the precondition check, personally - there's a difference between ArgumentNullException and NullReferenceException, and the former gives someone much more information - and tells them it's *their* fault, basically.

// cc @ivannaranjo @mmdriley @chrsmith @csells

**Comment by ivannaranjo** [comment]
I agree with the preconditions being a much cleaner exception when debugging the program, they are not meant to be catch really.
As for whether they should be sync or async it I would go with option 3 here, most of the preconditions will be able to be met synchronously but not sure if we can always guarantee them... That's why having nice error messages on the exceptions thrown from the preconditions can help immensely.

**Comment by mmdriley** [comment]
Eager precondition checking is good, but prefer simple code.

**Comment by jskeet** [comment]
I think we can close this now:

- Yes, validate the precondition.
- No, don't go out of our way to do so synchronously.
