### ISSUE TITLE
Allow directly specifying access_token to use in credentials

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/gcloud-dotnet#234]
Same issue for gcloud-dotnet as submitted for direct GoogleCredentials here:
https://github.com/google/google-api-dotnet-client/issues/761

basically, there are few scenarios where you can acquire an access_token on behalf of an end user and would need to access an api as that user.

**Comment by jskeet** [comment]
I don't think we need two issues for this - this project depends on the `Google.Apis.Auth` project which would be modified by that issue. (So if we fix it there, you'll be able to use that from this project.)
