### ISSUE TITLE
Optional parameters: yes or no?

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/gcloud-dotnet#41]
Currently every method we're creating ends up having at least 2 overloads, as there are always options - and async methods always have cancellation tokens (and sometimes progress reporters).

Now MS typically *doesn't* use optional parameters in the framework, presumably in order to support either languages which don't support them, or developers who dislike them. For example, the TAP guidelines always talk about overloads rather than having optional parameters.

An internal discussion suggested we'd start off by following the normal framework conventions - but as time goes on and we implement more methods, I'm feeling that the tangible pain of this (more overloads == more maintenance, risk of diverging docs, etc) is greater than the non-tangible benefit.

Thoughts?

(It's hard to gauge the community's view on this - most popular APIs were started before optional parameters were available. Roslyn uses them extensively in the public API though, at least for cancellation tokens.)

// cc @mmdriley @ivannaranjo @chrsmith @remi @SurferJeffAtGoogle

**Comment by SurferJeffAtGoogle** [comment]
Again, the fluent pattern comes to mind.

I am starting to see it in the new Asp.Net 5 code.  For example:
http://aspnetmvc.readthedocs.org/projects/mvc/en/latest/tutorials/mvc-with-entity-framework.html#configure-entity-framework

**Comment by jskeet** [comment]
The fluent pattern definitely works for some things, including configuration - I'm not sure it's as pleasant here. Fundamentally it always feels like a simple RPC should just be a single method call... if there were some nice way of making the "now execute" part implicit, that would be slightly different. There are ways it *could* be done using implicit conversions, but the idea of an implicit conversion making an RPC is horrible :)

**Comment by ivannaranjo** [comment]
Indeed the use of the fluent pattern is more appropriate for _builder_ kind of scenarios, like the configuration example, but not for a call, that is what we sort of have today with the existing .NET client, where you build a request and then execute it, and that is not that good.
I would rather vote for having the optional parameters, the IDE supports them quite well, the language now have the named parameters feature that works quite well with the optional parameters feature, combined the calls make a lot more sense now.

**Comment by mmdriley** [comment]
Intriguingly, Google's stance on optional parameters in C++ has just changed. As go the times, so must I.

I support using optional parameters. The obvious caveat applies: for a given function/argument, the default can *never* change since it would cause silent inconsistency in clients that haven't recompiled.

**Comment by jskeet** [comment]
Agreed. Perhaps we should have a list of "allowable default values", e.g.

- `null`
- `0`
- `default(CancellationToken)`
- `""`

It should definitely be used really, really sparingly.

**Comment by ivannaranjo** [comment]
Well, changing the defaults in parameters would mean changing the signature
which will be a breaking change, so yes we should be very careful about
that.
As for the allowed default values, I would say that things that come out of
`default(Type)` is the way to go. "" sincerely can just be checked with
`String.IsNullOrEmpty` so it is not a big deal.

**Comment by jskeet** [comment]
Looks like we mostly like them - will assume we're going with them for now, but we should listen for external feedback once we have more usage.
