### ISSUE TITLE
ListBuckets parameter "project" should be "projectId"

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [GoogleCloudPlatform/gcloud-dotnet#48]
Please rename the argument projectId.  The documentation uses the term project id.
https://cloud.google.com/storage/docs/projects?hl=en

**Comment by jskeet** [comment]
Just to clarify, this is in a call to `StorageClient.FromApplicationCredentials`? If so, I don't think that's the same value at all. It's the application name specified when specifying credentials. I've never personally used my project ID for that, and it's always been fine.

The parameter specified for listing and buckets is currently called `project` in the calls to `StorageClient.ListBuckets`. I could change that to `projectId` if that would be clearer.

**Comment by SurferJeffAtGoogle** [comment]
Ah, right.  "applicationName" is still confusing, but at least it's
consistent with all the other APIs and docs.

Yes, I think changing project to projectId in ListBuckets would be a small
improvement.

**Comment by jskeet** [comment]
(Renamed issue to make it clear this is no longer about applicationName.)
