### ISSUE TITLE
Ditch the "application name" part of the StorageClient construction

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/gcloud-dotnet#91]
Just use "gcloud-dotnet" as a hard-coded name.

**Comment by jskeet** [comment]
This was done in #111.

**Comment by Capstan** [comment]
Would we not want folks to allow customization of the User-Agent, which is what this is used for? And even if they do, wouldn't we want to append gcloud-dotnet/0.3 (or whatever the version is) anyway, to mark what version of the SDK they use?

**Comment by jskeet** [comment]
It still *allow* the customization of this - it's just somewhat hidden (`StorageClientImpl.ApplicationName`) because it isn't useful to most people.

For the gRPC-based libraries, we include more detailed version information, but at the moment I'm *only* including "gcloud-dotnet" as the application name. We could put the version number in if required though.
